In [2]:
import numpy as np

In [3]:
first_number = 56
second_number = 100

In [4]:
array = np.array((355,34,665,4,3,55))

In [5]:
print(array)

[355  34 665   4   3  55]


In [6]:
# Return values fro 2nd element to 5th
few = array[1:6]

In [8]:
print(few)

[ 34 665   4   3  55]


In [9]:
# Use these value and get the sq value
sq = (few * first_number) / second_number

In [11]:
print(sq)
print(few)

[ 19.04 372.4    2.24   1.68  30.8 ]
[ 34 665   4   3  55]
