In [2]:
import numpy as np

In [3]:
first_number = 56
secomd_number = 100

In [9]:
array = np.array((355,34,665,4,3,55))

In [10]:
print(array)

[355  34 665   4   3  55]


In [15]:
# Return values fro 2nd element to 5th
few = array[1:6]

In [14]:
print(few)

[665   4   3  55]


In [16]:
# Use these value and get the sq value
sq = few * 2

In [17]:
print(sq)

[  68 1330    8    6  110]
